version: "3.7"
services:
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 80:80
        depends_on:
            - web
            - cms
            - db
        volumes:
            - $PWD/default.conf:/etc/nginx/nginx.conf
            - /var/run/docker.sock:/tmp/docker.sock:ro

    web:
        build: frontend
        restart: unless-stopped

    cms:
        image: ghost:4-alpine
        restart: always
        depends_on:
            - db
        expose:
            - 2368
        environment:
            database__client: mysql
            database__connection__host: db
            database__connection__user: root
            database__connection__password: ghost
            database__connection__database: ghost
            url: http://0.0.0.0:2368

    db:
        image: mysql:5.7
        restart: always
        expose:
            - 3306
        volumes:
            - /data/cms/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ghost